# Project-wide variables that can be accessed from anywhere

# Path to Excel file with subject codes.
excel_codes: "data/raw/data.xlsx"

# Path to individual subjects' data.
data_dir: "data/raw/experiment_data"

# Path to file with the complete raw data.
complete_data_raw: "data/prep/groundhog_raw.RDS"

# Path to file with the cleaned data.
cleaned_data: "data/prep/groundhog_clean.RDS"

# Path to file used as input for HDDMRL.
hddmrl_data: "data/prep/groundhog_hddmrl_data.csv"
