# Project-wide variables that can be accessed from anywhere

# Path to Excel file with subject codes.
excel_codes: "data/raw/data.xlsx"

# Path to individual subjects' data.
data_dir: "data/raw/experiment_data"

# Path to file with the complete raw data.
complete_data_raw: "data/prep/groundhog_raw.RDS"

# Path to file with the cleaned data.
cleaned_data: "data/prep/groundhog_clean.RDS"

# Path to csv for brms output table; model:
# mood_pre ~ 1 + control + (1 + control | user_id) + (1 | ema_number)
brms_fit_1: "results/brms/fitted_models/brms_moodpre_1.RDS"
brms_table_1: "results/brms/tables/brms_moodpre_1.csv"
brms_fig_1: "results/brms/figures/brms_moodpre_1.pdf"

# Path to file used as input for HDDMRL.
hddmrl_data: "data/prep/groundhog_hddmrl_data.csv"
