title: "My Project's Title"
author: "M A G"
logo: images/logo.png

exclude_patterns: [_build, "**README**", "**.ipynb_checkpoints"] # to speed up jupyter-book's build
execute:
  execute_notebooks: "off"
  
repository:
  url: https://github.com/MiqG/project_template

html:
  use_repository_button: true
  use_issues_button: true
